server:
  port: 8001


mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.bgamq.boot.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloude2019
    username: root
    password: 123456
    dbcp2:
      min-idle: 5           #最小维持连接数
      initial-size: 5       #初始化连接数
      max-total: 5          #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间